Combining Dataframes

In [1]:
import pandas as pd

In [9]:
#Q1:Load both CSV files into separate DataFrames.
employee=pd.read_csv(r"C:\Users\Dell\Downloads\employees.csv")
employee

   employee_id   name department  salary
0          101  Rahul         IT   55000
1          102  Priya         HR   45000
2          103   Aman         IT   60000
3          104   Neha    Finance   52000
4          105   Riya  Marketing   48000

In [10]:
performance=pd.read_csv(r"C:\Users\Dell\Downloads\performance.csv")
performance

   employee_id  projects  rating  bonus
0          101         4     4.5   5000
1          102         3     4.0   3500
2          103         5     4.8   7000
3          104         4     4.2   4500
4          105         2     3.8   3000

In [38]:
#Q2:Create a new DataFrame by concatenating two employee DataFrames vertically.
df_concat=pd.concat([employee,performance],axis=0)
df_concat

   employee_id   name department   salary  projects  rating   bonus
0          101  Rahul         IT  55000.0       NaN     NaN     NaN
1          102  Priya         HR  45000.0       NaN     NaN     NaN
2          103   Aman         IT  60000.0       NaN     NaN     NaN
3          104   Neha    Finance  52000.0       NaN     NaN     NaN
4          105   Riya  Marketing  48000.0       NaN     NaN     NaN
0          101    NaN        NaN      NaN       4.0     4.5  5000.0
1          102    NaN        NaN      NaN       3.0     4.0  3500.0
2          103    NaN        NaN      NaN       5.0     4.8  7000.0
3          104    NaN        NaN      NaN       4.0     4.2  4500.0
4          105    NaN        NaN      NaN       2.0     3.8  3000.0

In [39]:
#Q3:Concatenate them while resetting the index.
df_index= pd.concat([employee, performance], axis=0, ignore_index=True)
df_index

   employee_id   name department   salary  projects  rating   bonus
0          101  Rahul         IT  55000.0       NaN     NaN     NaN
1          102  Priya         HR  45000.0       NaN     NaN     NaN
2          103   Aman         IT  60000.0       NaN     NaN     NaN
3          104   Neha    Finance  52000.0       NaN     NaN     NaN
4          105   Riya  Marketing  48000.0       NaN     NaN     NaN
5          101    NaN        NaN      NaN       4.0     4.5  5000.0
6          102    NaN        NaN      NaN       3.0     4.0  3500.0
7          103    NaN        NaN      NaN       5.0     4.8  7000.0
8          104    NaN        NaN      NaN       4.0     4.2  4500.0
9          105    NaN        NaN      NaN       2.0     3.8  3000.0

In [40]:
#Q4:Concatenate two DataFrames horizontally and observe the result.
df_1 = pd.concat([employee, performance], axis=1)
df_1

   employee_id   name department  salary  employee_id  projects  rating  bonus
0          101  Rahul         IT   55000          101         4     4.5   5000
1          102  Priya         HR   45000          102         3     4.0   3500
2          103   Aman         IT   60000          103         5     4.8   7000
3          104   Neha    Finance   52000          104         4     4.2   4500
4          105   Riya  Marketing   48000          105         2     3.8   3000

In [41]:
#Q5:Merge employees.csv and performance.csv using employee_id.
df_merge=pd.merge(employee,performance,on="employee_id")
df_merge

   employee_id   name department  salary  projects  rating  bonus
0          101  Rahul         IT   55000         4     4.5   5000
1          102  Priya         HR   45000         3     4.0   3500
2          103   Aman         IT   60000         5     4.8   7000
3          104   Neha    Finance   52000         4     4.2   4500
4          105   Riya  Marketing   48000         2     3.8   3000

In [42]:
#Q6:Perform a left merge using employee_id.
df_left=pd.merge(employee,performance,on="employee_id",how="left")
df_left

   employee_id   name department  salary  projects  rating  bonus
0          101  Rahul         IT   55000         4     4.5   5000
1          102  Priya         HR   45000         3     4.0   3500
2          103   Aman         IT   60000         5     4.8   7000
3          104   Neha    Finance   52000         4     4.2   4500
4          105   Riya  Marketing   48000         2     3.8   3000

In [43]:
#Q7:Perform a right merge using employee_id.
df_right=pd.merge(employee,performance,on="employee_id",how="right")
df_right

   employee_id   name department  salary  projects  rating  bonus
0          101  Rahul         IT   55000         4     4.5   5000
1          102  Priya         HR   45000         3     4.0   3500
2          103   Aman         IT   60000         5     4.8   7000
3          104   Neha    Finance   52000         4     4.2   4500
4          105   Riya  Marketing   48000         2     3.8   3000

In [44]:
#Q8:Perform an inner merge using employee_id
df_inner=pd.merge(employee,performance,on="employee_id",how="inner")
df_inner

   employee_id   name department  salary  projects  rating  bonus
0          101  Rahul         IT   55000         4     4.5   5000
1          102  Priya         HR   45000         3     4.0   3500
2          103   Aman         IT   60000         5     4.8   7000
3          104   Neha    Finance   52000         4     4.2   4500
4          105   Riya  Marketing   48000         2     3.8   3000

In [47]:
#Q9:Perform an outer merge using employee_id.
df=pd.merge(employee,performance,on="employee_id",how="outer")
df

   employee_id   name department  salary  projects  rating  bonus
0          101  Rahul         IT   55000         4     4.5   5000
1          102  Priya         HR   45000         3     4.0   3500
2          103   Aman         IT   60000         5     4.8   7000
3          104   Neha    Finance   52000         4     4.2   4500
4          105   Riya  Marketing   48000         2     3.8   3000

In [48]:
#Q10:After merging, calculate the total compensation = salary + bonus for every employee.
df["total_compensation"] = df["salary"] + df["bonus"]
df

,employee_id,name,department,salary,projects,rating,bonus,total_compensation
0,101,Rahul,IT,55000,4,4.5,5000,60000
1,102,Priya,HR,45000,3,4.0,3500,48500
2,103,Aman,IT,60000,5,4.8,7000,67000
3,104,Neha,Finance,52000,4,4.2,4500,56500
4,105,Riya,Marketing,48000,2,3.8,3000,51000

In [49]:
#Q11:Find the employee with the highest performance rating.
df.loc[df["rating"].idxmax()]

employee_id             103
name                   Aman
department               IT
salary                60000
projects                  5
rating                  4.8
bonus                  7000
total_compensation    67000
Name: 2, dtype: object

In [52]:
#Q12:Find employees who have completed more than 3 projects.
df[df["projects"] > 3].groupby("name")["projects"].sum()

name
Aman     5
Neha     4
Rahul    4
Name: projects, dtype: int64

In [53]:
#Q13:Find the average salary of employees whose rating is greater than 4.0.
df[df["rating"] > 4.0].groupby("name")["salary"].mean()

name
Aman     60000.0
Neha     52000.0
Rahul    55000.0
Name: salary, dtype: float64

In [57]:
#Q14:Find the department with the highest average salary.
df.groupby("department")["salary"].mean().sort_values(ascending=False).head(1)

department
IT    57500.0
Name: salary, dtype: float64

In [58]:
#Q15:Sort the merged DataFrame by rating from highest to lowest.
df.sort_values("rating",ascending=False)

,employee_id,name,department,salary,projects,rating,bonus,total_compensation
2,103,Aman,IT,60000,5,4.8,7000,67000
0,101,Rahul,IT,55000,4,4.5,5000,60000
3,104,Neha,Finance,52000,4,4.2,4500,56500
1,102,Priya,HR,45000,3,4.0,3500,48500
4,105,Riya,Marketing,48000,2,3.8,3000,51000

In [59]:
#Q16:Suppose a third CSV called attendance.csv.Load it and merge all three DataFrames using employee_id
attendance=pd.read_csv(r"C:\Users\Dell\Downloads\attendance.csv")
attendance

   employee_id  days_present
0          101            24
1          102            22
2          103            26
3          104            23
4          105            20

In [61]:
df3=pd.merge(df_merge,attendance,on="employee_id")
df3

,employee_id,name,department,salary,projects,rating,bonus,days_present
0,101,Rahul,IT,55000,4,4.5,5000,24
1,102,Priya,HR,45000,3,4.0,3500,22
2,103,Aman,IT,60000,5,4.8,7000,26
3,104,Neha,Finance,52000,4,4.2,4500,23
4,105,Riya,Marketing,48000,2,3.8,3000,20

In [70]:
#Q17:Calculate a new column:performance_score = rating × projects
df3["performance_score"]=df3["rating"]*df3["projects"]
df

,employee_id,name,department,salary,projects,rating,bonus,total_compensation,performance_score
0,101,Rahul,IT,55000,4,4.5,5000,60000,18.0
1,102,Priya,HR,45000,3,4.0,3500,48500,12.0
2,103,Aman,IT,60000,5,4.8,7000,67000,24.0
3,104,Neha,Finance,52000,4,4.2,4500,56500,16.8
4,105,Riya,Marketing,48000,2,3.8,3000,51000,7.6

In [71]:
#Q18:Find the employee who has the highest performance score.
df3.loc[df3["performance_score"].idxmax()]

employee_id            103
name                  Aman
department              IT
salary               60000
projects                 5
rating                 4.8
bonus                 7000
days_present            26
performance_score     24.0
Name: 2, dtype: object

In [68]:
#Q19:Find employees whose:rating > 4,projects > 3,days_present > 22
df3[(df3["rating"]>4)&(df3['projects']>3)&(df3['days_present']>22)]

,employee_id,name,department,salary,projects,rating,bonus,days_present
0,101,Rahul,IT,55000,4,4.5,5000,24
2,103,Aman,IT,60000,5,4.8,7000,26
3,104,Neha,Finance,52000,4,4.2,4500,23

In [72]:
'''Q20:Create a final DataFrame containing only:
employee_id, name, department, salary, bonus, rating, projects, days_present, performance_score'''

df3 = df3[["employee_id","name","department","salary","bonus","rating","projects",
        "days_present","performance_score"]]
df3

,employee_id,name,department,salary,bonus,rating,projects,days_present,performance_score
0,101,Rahul,IT,55000,5000,4.5,4,24,18.0
1,102,Priya,HR,45000,3500,4.0,3,22,12.0
2,103,Aman,IT,60000,7000,4.8,5,26,24.0
3,104,Neha,Finance,52000,4500,4.2,4,23,16.8
4,105,Riya,Marketing,48000,3000,3.8,2,20,7.6