Filtering Rows And Columns

In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Downloads\pandas_filtering_practice_dataset.csv")
df.head(5)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497

In [6]:
#Q1:Select only the Customer and City columns.
df.filter(items=['Customer','City'])

       Customer       City
0   Customer_01      Delhi
1   Customer_02       Pune
2   Customer_03      Delhi
3   Customer_04    Chennai
4   Customer_05  Hyderabad
5   Customer_06      Delhi
6   Customer_07    Chennai
7   Customer_08  Hyderabad
8   Customer_09    Chennai
9   Customer_10  Hyderabad
10  Customer_11    Kolkata
11  Customer_12  Hyderabad
12  Customer_13       Pune
13  Customer_14      Delhi
14  Customer_15  Hyderabad
15  Customer_16    Kolkata
16  Customer_17    Chennai
17  Customer_18       Pune
18  Customer_19  Hyderabad
19  Customer_20     Mumbai
20  Customer_21       Pune
21  Customer_22    Chennai
22  Customer_23      Delhi
23  Customer_24      Delhi
24  Customer_25     Mumbai
25  Customer_26    Chennai
26  Customer_27  Hyderabad
27  Customer_28     Mumbai
28  Customer_29      Delhi
29  Customer_30  Hyderabad
30  Customer_31  Hyderabad
31  Customer_32  Bangalore
32  Customer_33  Hyderabad
33  Customer_34    Chennai
34  Customer_35      Delhi
35  Customer_36  Bangalore
36  Customer_37       Pune
37  Customer_38     Mumbai
38  Customer_39      Delhi
39  Customer_40  Bangalore
40  Customer_41  Hyderabad
41  Customer_42  Bangalore
42  Customer_43      Delhi
43  Customer_44      Delhi
44  Customer_45  Bangalore
45  Customer_46  Hyderabad
46  Customer_47     Mumbai
47  Customer_48  Bangalore
48  Customer_49  Bangalore
49  Customer_50      Delhi

In [7]:
#Q2:Select Product, Price, and Rating columns.
df.filter(items=['Product','Price','Rating'])

            Product  Price  Rating
0        Smartphone   1499     2.8
1          Keyboard    499     2.7
2          Football   2999     3.1
3          Sneakers   1999     2.9
4            Laptop   2499     4.0
5     Tennis Racket   1999     4.6
6           T-Shirt   1499     4.4
7        Smartphone   2499     2.9
8             Chair    999     3.8
9   AI Fundamentals   1499     4.2
10       Smartphone   1999     2.7
11        SQL Guide   1999     2.8
12        SQL Guide   1499     5.0
13    Python Basics    999     4.1
14         Keyboard   3999     3.8
15         Yoga Mat    799     3.2
16       Smartphone    999     3.8
17         Football   2499     4.4
18            Chair   2499     4.7
19           Laptop   3999     4.5
20     Data Science   2999     4.9
21  AI Fundamentals   3999     2.8
22             Lamp   1499     2.5
23       Smartphone   1499     3.2
24    Tennis Racket   3999     4.5
25         Keyboard   2999     3.5
26       Smartphone   1499     3.0
27  AI Fundamentals   1499     4.7
28      Cricket Bat    499     4.9
29        SQL Guide   2999     4.8
30       Smartphone   1999     3.6
31            Jeans    499     4.4
32         Football    799     4.6
33       Headphones    799     4.9
34      Cricket Bat   2499     4.8
35         Sneakers   1999     3.6
36    Python Basics   1499     3.8
37       Smartphone    999     3.6
38         Yoga Mat    999     3.2
39           Jacket   1499     4.3
40         Yoga Mat    799     4.1
41       Headphones    999     4.4
42           Laptop    499     4.6
43           Jacket    499     4.7
44         Keyboard    999     4.8
45          T-Shirt   2499     4.5
46            Chair    499     4.6
47  AI Fundamentals   1499     2.6
48            Chair   2499     4.1
49            Chair    999     4.0

In [8]:
#Q3:Filter all orders where Price > 2000.
df[df['Price']>2000]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497

In [9]:
#Q4:Filter all orders where Rating >= 4.
df[df['Rating']>=4]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997

In [10]:
#Q5:Filter all orders where Quantity >= 3.
df[df['Quantity']>=3]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997

In [11]:
#Q6:Show only orders where Order_Status == 'Delivered'.
df[df['Order_Status']=='Delivered']

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997

In [12]:
#Q7:Find orders where:Price > 2000 AND Rating >= 4
df[(df['Price']>2000) & (df['Rating']>=4)]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497

In [16]:
#Q8:Find orders from Delhi OR Mumbai.
df[df['City'].isin (['Delhi','Mumbai'])]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997

In [18]:
#Q9:Find orders where:Price is between 1000 and 3000 AND Rating >= 4
df[(df['Price'].between(1000,3000) & (df['Rating']>=4))]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497

In [21]:
#Q10:Find Delivered orders where Total_Amount > 5000.
df[(df['Order_Status']=='Delivered') & (df['Total_Amount']>5000)]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495

In [23]:
#Q11:Find orders from Delhi, Mumbai, or Hyderabad.
df[df['City'].isin(['Delhi','Mumbai','Hyderabad'])]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997

In [25]:
#Q12:Find orders where:City is Delhi AND Price > 1500 AND Order_Status is Delivered
df[(df['City']=='Delhi') & (df['Price']>1500) & (df['Order_Status']=='Delivered')]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996

In [26]:
#Q13:Show only Order_ID, Customer, Product, and Price for orders where Price > 2500.
df[df['Price']>2500][['Order_ID','Customer','Product','Price']]

   Order_ID     Customer          Product  Price
2    ORD003  Customer_03         Football   2999
14   ORD015  Customer_15         Keyboard   3999
19   ORD020  Customer_20           Laptop   3999
20   ORD021  Customer_21     Data Science   2999
21   ORD022  Customer_22  AI Fundamentals   3999
24   ORD025  Customer_25    Tennis Racket   3999
25   ORD026  Customer_26         Keyboard   2999
29   ORD030  Customer_30        SQL Guide   2999

In [33]:
#Q14:Show Customer, City, and Total_Amount for customers from Delhi who have Rating >= 4.
df[(df['City']=='Delhi') & (df['Rating']>=4)][['Customer','City','Total_Amount']]

       Customer   City  Total_Amount
5   Customer_06  Delhi          1999
13  Customer_14  Delhi           999
28  Customer_29  Delhi          2495
34  Customer_35  Delhi          9996
42  Customer_43  Delhi           998
43  Customer_44  Delhi          1497
49  Customer_50  Delhi          2997

In [37]:
#Q15:Show Order_ID, Product, Quantity, and Total_Amount for Delivered orders having Quantity >= 2.
df.loc[(df['Order_Status']=='Delivered') & (df['Quantity']>=2),['Order_ID','Product','Quantity','Total_Amount']]

   Order_ID          Product  Quantity  Total_Amount
2    ORD003         Football         5         14995
3    ORD004         Sneakers         3          5997
7    ORD008       Smartphone         4          9996
8    ORD009            Chair         5          4995
9    ORD010  AI Fundamentals         5          7495
10   ORD011       Smartphone         4          7996
14   ORD015         Keyboard         5         19995
16   ORD017       Smartphone         5          4995
20   ORD021     Data Science         3          8997
21   ORD022  AI Fundamentals         4         15996
22   ORD023             Lamp         5          7495
24   ORD025    Tennis Racket         2          7998
25   ORD026         Keyboard         3          8997
28   ORD029      Cricket Bat         5          2495
30   ORD031       Smartphone         4          7996
34   ORD035      Cricket Bat         4          9996
35   ORD036         Sneakers         2          3998
39   ORD040           Jacket         5          7495
43   ORD044           Jacket         3          1497
44   ORD045         Keyboard         5          4995
45   ORD046          T-Shirt         2          4998
46   ORD047            Chair         4          1996
49   ORD050            Chair         3          2997

In [38]:
#Q16:Show Customer, City, Product, and Rating for orders where the city is Delhi or Mumbai and rating is at least 4.
df[(df['City'].isin(['Delhi','Mumbai'])) & (df['Rating']>=4)][[
    'Customer','City','Product','Rating']]

       Customer    City          Product  Rating
5   Customer_06   Delhi    Tennis Racket     4.6
13  Customer_14   Delhi    Python Basics     4.1
19  Customer_20  Mumbai           Laptop     4.5
24  Customer_25  Mumbai    Tennis Racket     4.5
27  Customer_28  Mumbai  AI Fundamentals     4.7
28  Customer_29   Delhi      Cricket Bat     4.9
34  Customer_35   Delhi      Cricket Bat     4.8
42  Customer_43   Delhi           Laptop     4.6
43  Customer_44   Delhi           Jacket     4.7
46  Customer_47  Mumbai            Chair     4.6
49  Customer_50   Delhi            Chair     4.0

In [39]:
'''Q17:Show Order_ID, Customer, Price, and Rating for orders where:
Price is between 1000–3000
Rating >= 4
Status = Delivered'''

df[df['Price'].between(1000,3000) & (df['Rating']>=4) &(df['Order_Status']=='Delivered')][[
    'Order_ID','Customer','Price','Rating']]

   Order_ID     Customer  Price  Rating
6    ORD007  Customer_07   1499     4.4
9    ORD010  Customer_10   1499     4.2
18   ORD019  Customer_19   2499     4.7
20   ORD021  Customer_21   2999     4.9
34   ORD035  Customer_35   2499     4.8
39   ORD040  Customer_40   1499     4.3
45   ORD046  Customer_46   2499     4.5

In [45]:
#Q18:Find all orders where the city is not Delhi and Rating >= 4.
df.loc[(df['City'] != 'Delhi') & (df['Rating'] >= 4),
    ['Customer', 'City', 'Rating']]

       Customer       City  Rating
4   Customer_05  Hyderabad     4.0
6   Customer_07    Chennai     4.4
9   Customer_10  Hyderabad     4.2
12  Customer_13       Pune     5.0
17  Customer_18       Pune     4.4
18  Customer_19  Hyderabad     4.7
19  Customer_20     Mumbai     4.5
20  Customer_21       Pune     4.9
24  Customer_25     Mumbai     4.5
27  Customer_28     Mumbai     4.7
29  Customer_30  Hyderabad     4.8
31  Customer_32  Bangalore     4.4
32  Customer_33  Hyderabad     4.6
33  Customer_34    Chennai     4.9
39  Customer_40  Bangalore     4.3
40  Customer_41  Hyderabad     4.1
41  Customer_42  Bangalore     4.4
44  Customer_45  Bangalore     4.8
45  Customer_46  Hyderabad     4.5
46  Customer_47     Mumbai     4.6
48  Customer_49  Bangalore     4.1

In [47]:
'''Q19:Find orders where:
City is Delhi, Mumbai, or Hyderabad
Price is between 1000–3000
Rating >= 4
Status = Delivered'''

df.loc[ df['City'].isin(['Delhi','Mumbai','Hyderabad']) & df['Price'].between(1000, 3000) &
    (df['Rating'] >= 4) & (df['Order_Status'] == 'Delivered'),['Order_ID', 
    'Customer', 'Product', 'Total_Amount']]

   Order_ID     Customer          Product  Total_Amount
9    ORD010  Customer_10  AI Fundamentals          7495
18   ORD019  Customer_19            Chair          2499
34   ORD035  Customer_35      Cricket Bat          9996
45   ORD046  Customer_46          T-Shirt          4998

In [49]:
'''Q20:Final challenge: Return only:
Order_ID, Customer, City, Product, Quantity, Price, Rating, Total_Amount
for orders that satisfy all of these:Price >= 1500,Rating >= 4,
Quantity >= 2,City is Delhi or Mumbai,Order_Status is Delivered'''

df.loc[(df['City'].isin(['Delhi','Mumbai'])) & (df['Price']>=1500) &(df['Rating']>=4)&
    (df['Quantity']>=2) & (df['Order_Status']=='Delivered'),['Order_ID','Customer',
        'City','Product','Quantity','Price','Rating','Total_Amount']]

,Order_ID,Customer,City,Product,Quantity,Price,Rating,Total_Amount
24,ORD025,Customer_25,Mumbai,Tennis Racket,2,3999,4.5,7998
34,ORD035,Customer_35,Delhi,Cricket Bat,4,2499,4.8,9996