Groupby And Aggregating

In [4]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Downloads\groupby_practice_ecommerce_dataset.csv")
df.head(5)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000

In [12]:
#Q1:Find the total number of orders for each City.
df.groupby('City').size()

City
Delhi     10
Mumbai    10
Pune      10
dtype: int64

In [13]:
#Q2:Find the total number of orders for each Category.
df.groupby('Category').size()

Category
Clothing        8
Electronics    15
Home            7
dtype: int64

In [14]:
#Q3:Find the number of orders for each Payment_Mode.
df.groupby('Payment_Mode').size()

Payment_Mode
Card     8
Cash     7
UPI     15
dtype: int64

In [15]:
#Q4:Find the average Rating for each Category.
df.groupby('Category')['Rating'].mean()

Category
Clothing       3.625000
Electronics    4.066667
Home           4.000000
Name: Rating, dtype: float64

In [16]:
#Q5:Find the average Rating for each City.
df.groupby('City')['Rating'].mean()

City
Delhi     4.2
Mumbai    3.9
Pune      3.7
Name: Rating, dtype: float64

In [17]:
#Q6:Find the total Sales for each City.
df.groupby('City')['Sales'].sum()

City
Delhi     162000
Mumbai    135800
Pune      103300
Name: Sales, dtype: int64

In [18]:
#Q7:Find the total Sales for each Category
df.groupby('Category')['Sales'].sum()

Category
Clothing        18400
Electronics    355300
Home            27400
Name: Sales, dtype: int64

In [19]:
#Q8:Find the average Sales for each Category.
df.groupby('Category')['Sales'].mean()

Category
Clothing        2300.000000
Electronics    23686.666667
Home            3914.285714
Name: Sales, dtype: float64

In [20]:
#Q9:Find the maximum Sales for each City.
df.groupby('City')['Sales'].max()

City
Delhi     58000
Mumbai    60000
Pune      52000
Name: Sales, dtype: int64

In [21]:
#Q10:Find the minimum Sales for each Category.
df.groupby('Category')['Sales'].min()

Category
Clothing       1100
Electronics    1600
Home           3000
Name: Sales, dtype: int64

In [25]:
#Q11:Find the total Sales for each City and Category.
df.groupby(['City','Category'])['Sales'].sum()

City    Category
Delhi   Clothing         6800
        Electronics    147400
        Home             7800
Mumbai  Clothing         7100
        Electronics    121400
        Home             7300
Pune    Clothing         4500
        Electronics     86500
        Home            12300
Name: Sales, dtype: int64

In [26]:
#Q12:Find the average Rating for each City and Category.
df.groupby(['City','Category'])['Rating'].mean()

City    Category
Delhi   Clothing       3.666667
        Electronics    4.400000
        Home           4.500000
Mumbai  Clothing       4.333333
        Electronics    4.000000
        Home           3.000000
Pune    Clothing       2.500000
        Electronics    3.800000
        Home           4.333333
Name: Rating, dtype: float64

In [28]:
#Q13:Find the number of orders for each City and Payment_Mode
df.groupby(['City','Payment_Mode']).size()

City    Payment_Mode
Delhi   Card            2
        Cash            3
        UPI             5
Mumbai  Card            3
        Cash            2
        UPI             5
Pune    Card            3
        Cash            2
        UPI             5
dtype: int64

In [29]:
#Q14:Find the total Sales for each Category and Payment_Mode.
df.groupby(['Category','Payment_Mode'])['Sales'].sum()

Category     Payment_Mode
Clothing     Card              1200
             Cash             17200
Electronics  Card            256500
             UPI              98800
Home         Card              4500
             UPI              22900
Name: Sales, dtype: int64

In [30]:
#Q15:Find the number of orders for each Order_Status and Payment_Mode.
df.groupby(['Order_Status','Payment_Mode']).size()

Order_Status  Payment_Mode
Cancelled     Card             2
              Cash             2
              UPI              2
Delivered     Card             6
              Cash             5
              UPI             13
dtype: int64

In [32]:
#Q16:Find the total sales and average sales for each Category.
df.groupby('Category')['Sales'].agg(['sum','mean'])

                sum          mean
Category
Clothing      18400   2300.000000
Electronics  355300  23686.666667
Home          27400   3914.285714

In [33]:
#Q17:Find the minimum, maximum and average rating for each Category.
df.groupby('Category')['Rating'].agg(['min','max','mean'])

             min  max      mean
Category
Clothing       2    5  3.625000
Electronics    2    5  4.066667
Home           2    5  4.000000

In [35]:
#Q18:Find the total number of orders and total sales for each City.
df.groupby('City')['Sales'].agg(['size','sum'])

        size     sum
City
Delhi     10  162000
Mumbai    10  135800
Pune      10  103300

In [42]:
#Q19:Find the number of orders for each Product, and identify which product has the highest number of orders.
order_count = df.groupby('Product').size()
order_count.sort_values(ascending=False)

Product
Headphones    4
Laptop        4
Mixer         4
Mobile        4
Chair         3
Jacket        3
Keyboard      3
T-Shirt       3
Jeans         2
dtype: int64

In [43]:
#Q20:Find the total sales for each City only for Delivered orders.
df[df['Order_Status']=='Delivered'].groupby('City')['Sales'].sum()

City
Delhi     157200
Mumbai    102600
Pune       47900
Name: Sales, dtype: int64

In [45]:
#Q21:Find the top 5 cities by total sales.
df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(5)

City
Delhi     162000
Mumbai    135800
Pune      103300
Name: Sales, dtype: int64

In [48]:
#Q22:Find the category with the highest average rating.
df.groupby('Category')['Rating'].mean().sort_values(ascending=False).head(1)

Category
Electronics    4.066667
Name: Rating, dtype: float64

In [55]:
#Q23:Find products having more than 10 orders
order_count = df.groupby('Product').size()
order_count[order_count > 10]

Series([], dtype: int64)

In [59]:
#Q24:Find cities where total sales are greater than ₹50,000.
order_sales=df.groupby('City')['Sales'].sum()
order_sales[order_sales>50000]

City
Delhi     162000
Mumbai    135800
Pune      103300
Name: Sales, dtype: int64

In [60]:
#Q25:Find the top 3 products by number of orders.
df.groupby('Product').size().sort_values(ascending=False).head(3)

Product
Headphones    4
Laptop        4
Mixer         4
dtype: int64

In [61]:
#Q26:Find the payment mode generating the highest sales.
df.groupby('Payment_Mode')['Sales'].sum().sort_values(ascending=False).head(1)

Payment_Mode
Card    262200
Name: Sales, dtype: int64

In [67]:
#Q27:Find the category with the lowest average rating.
df.groupby('Category')['Rating'].mean().sort_values(ascending=True).head(1)

Category
Clothing    3.625
Name: Rating, dtype: float64

In [69]:
#Q28:Find delivered orders and identify the city with the highest sales.
df[df['Order_Status']=='Delivered'].groupby('City')['Sales'].sum().sort_values(ascending=False).head(1)

City
Delhi    157200
Name: Sales, dtype: int64

In [66]:
#Q29:Find the top 3 categories by total sales.
df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(3)

Category
Electronics    355300
Home            27400
Clothing        18400
Name: Sales, dtype: int64

In [71]:
#Q30:Find products whose average rating is greater than 4.
avg_rating=df.groupby('Product')['Rating'].mean()
avg_rating[avg_rating>4]

Product
Chair         4.333333
Headphones    4.250000
Laptop        4.250000
Name: Rating, dtype: float64