In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Downloads\missing_duplicate_practice.csv")
df.head(5)

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.2,Electronics,UPI,Delivered
1,102,Diya,Mumbai,NaN,4.5,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,NaN,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,NaN,4.1,Clothing,NaN,Cancelled

In [2]:
#Q1:Check the dataset for missing values.
df.isnull()

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,True,False
5,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False
8,False,False,False,False,True,False,False,False
9,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False
13,False,False,False,False,False,False,False,False

In [3]:
#Q2:Find the number of missing values in each column.
df.isnull().sum()

Order_ID        0
Name            0
City            0
Sales           3
Rating          4
Category        0
Payment_Mode    2
Order_Status    0
dtype: int64

In [10]:
#Q3:Find the total number of missing values in the entire DataFrame.
df.isnull().sum().sum()

np.int64(9)

In [8]:
#Q4:Remove all rows containing missing values.
df.dropna()

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.2,Electronics,UPI,Delivered
3,104,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
6,107,Rohan,Pune,6800.0,4.0,Grocery,Cash,Delivered
10,111,Arjun,Delhi,4500.0,3.9,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
13,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered

In [9]:
#Q5:Remove columns containing missing values.
df.dropna(axis=1)

    Order_ID    Name    City     Category Order_Status
0        101   Aarav   Delhi  Electronics    Delivered
1        102    Diya  Mumbai     Clothing    Delivered
2        103   Rohan    Pune      Grocery      Pending
3        104   Meera   Delhi  Electronics    Delivered
4        105   Kabir  Mumbai     Clothing    Cancelled
5        106   Anaya    Pune      Grocery    Delivered
6        107   Rohan    Pune      Grocery    Delivered
7        108  Ishita   Delhi  Electronics      Pending
8        109  Vivaan  Mumbai     Clothing    Delivered
9        110    Diya  Mumbai     Clothing    Delivered
10       111   Arjun   Delhi  Electronics    Delivered
11       112   Meera   Delhi  Electronics    Delivered
12       103   Rohan    Pune      Grocery      Pending
13       112   Meera   Delhi  Electronics    Delivered

In [11]:
#Q6:Create a new DataFrame where rows with missing values in Sales are removed.
df.dropna(subset=['Sales'])

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.2,Electronics,UPI,Delivered
2,103,Rohan,Pune,6800.0,NaN,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
5,106,Anaya,Pune,7200.0,NaN,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.0,Grocery,Cash,Delivered
8,109,Vivaan,Mumbai,6100.0,NaN,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.3,Clothing,NaN,Delivered
10,111,Arjun,Delhi,4500.0,3.9,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
12,103,Rohan,Pune,6800.0,NaN,Grocery,Cash,Pending
13,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered

In [12]:
#Q7:Replace all missing values with 0.
df.fillna(0)

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.2,Electronics,UPI,Delivered
1,102,Diya,Mumbai,0.0,4.5,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,0.0,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,0.0,4.1,Clothing,0,Cancelled
5,106,Anaya,Pune,7200.0,0.0,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.0,Grocery,Cash,Delivered
7,108,Ishita,Delhi,0.0,4.6,Electronics,UPI,Pending
8,109,Vivaan,Mumbai,6100.0,0.0,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.3,Clothing,0,Delivered
10,111,Arjun,Delhi,4500.0,3.9,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
12,103,Rohan,Pune,6800.0,0.0,Grocery,Cash,Pending
13,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered

In [16]:
#Q8:Fill missing values in Sales with the average Sales.
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())
df

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.2,Electronics,UPI,Delivered
1,102,Diya,Mumbai,5700.0,4.5,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,NaN,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,5700.0,4.1,Clothing,NaN,Cancelled
5,106,Anaya,Pune,7200.0,NaN,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.0,Grocery,Cash,Delivered
7,108,Ishita,Delhi,5700.0,4.6,Electronics,UPI,Pending
8,109,Vivaan,Mumbai,6100.0,NaN,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.3,Clothing,NaN,Delivered
10,111,Arjun,Delhi,4500.0,3.9,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered
12,103,Rohan,Pune,6800.0,NaN,Grocery,Cash,Pending
13,112,Meera,Delhi,4500.0,3.9,Electronics,UPI,Delivered

In [17]:
#Q9:Fill missing values in Rating with the average Rating
df['Rating']=df['Rating'].fillna(df['Rating'].mean())
df

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.20,Electronics,UPI,Delivered
1,102,Diya,Mumbai,5700.0,4.50,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,4.13,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,5700.0,4.10,Clothing,NaN,Cancelled
5,106,Anaya,Pune,7200.0,4.13,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.00,Grocery,Cash,Delivered
7,108,Ishita,Delhi,5700.0,4.60,Electronics,UPI,Pending
8,109,Vivaan,Mumbai,6100.0,4.13,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.30,Clothing,NaN,Delivered
10,111,Arjun,Delhi,4500.0,3.90,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered
12,103,Rohan,Pune,6800.0,4.13,Grocery,Cash,Pending
13,112,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered

In [21]:
#Q10:Fill missing values in Payment_Mode with "Unknown".
df['Payment_Mode']=df['Payment_Mode'].fillna('Unknown')
df

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.20,Electronics,UPI,Delivered
1,102,Diya,Mumbai,5700.0,4.50,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,4.13,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,5700.0,4.10,Clothing,Unknown,Cancelled
5,106,Anaya,Pune,7200.0,4.13,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.00,Grocery,Cash,Delivered
7,108,Ishita,Delhi,5700.0,4.60,Electronics,UPI,Pending
8,109,Vivaan,Mumbai,6100.0,4.13,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.30,Clothing,Unknown,Delivered
10,111,Arjun,Delhi,4500.0,3.90,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered
12,103,Rohan,Pune,6800.0,4.13,Grocery,Cash,Pending
13,112,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered

In [22]:
#Q11:Check which rows are duplicates.
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
dtype: bool

In [23]:
#Q12:Count the total number of duplicate rows.
df.duplicated().sum()

np.int64(2)

In [24]:
#Q13:Remove all duplicate rows.
df.drop_duplicates()

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.20,Electronics,UPI,Delivered
1,102,Diya,Mumbai,5700.0,4.50,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,4.13,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,5700.0,4.10,Clothing,Unknown,Cancelled
5,106,Anaya,Pune,7200.0,4.13,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.00,Grocery,Cash,Delivered
7,108,Ishita,Delhi,5700.0,4.60,Electronics,UPI,Pending
8,109,Vivaan,Mumbai,6100.0,4.13,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.30,Clothing,Unknown,Delivered
10,111,Arjun,Delhi,4500.0,3.90,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered

In [26]:
#Q14:After removing duplicates, check how many rows remain.
df.drop_duplicates().shape[0]

12

In [28]:
'''Q15: Clean the complete dataset:
Find missing values.
Fill missing Sales with its mean.
Fill missing Rating with its mean.
Fill missing Payment_Mode with "Unknown".
Remove duplicate rows.
Display the final cleaned DataFrame.'''
df.isnull()
df['Sales']=df['Sales'].fillna(df['Sales'].mean())
df['Rating']=df['Rating'].fillna(df['Rating'].mean())
df['Payment_Mode']=df['Payment_Mode'].fillna('Unknown')
df = df.drop_duplicates()
df

,Order_ID,Name,City,Sales,Rating,Category,Payment_Mode,Order_Status
0,101,Aarav,Delhi,5200.0,4.20,Electronics,UPI,Delivered
1,102,Diya,Mumbai,5700.0,4.50,Clothing,Card,Delivered
2,103,Rohan,Pune,6800.0,4.13,Grocery,Cash,Pending
3,104,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered
4,105,Kabir,Mumbai,5700.0,4.10,Clothing,Unknown,Cancelled
5,106,Anaya,Pune,7200.0,4.13,Grocery,Card,Delivered
6,107,Rohan,Pune,6800.0,4.00,Grocery,Cash,Delivered
7,108,Ishita,Delhi,5700.0,4.60,Electronics,UPI,Pending
8,109,Vivaan,Mumbai,6100.0,4.13,Clothing,Card,Delivered
9,110,Diya,Mumbai,5800.0,4.30,Clothing,Unknown,Delivered
10,111,Arjun,Delhi,4500.0,3.90,Electronics,UPI,Delivered
11,112,Meera,Delhi,4500.0,3.90,Electronics,UPI,Delivered