In [1]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul', 'Priya', 'Neha'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai'],
    'Sales': [5000, 7000, 3000, 8000, 6000],
    'Rating': [4.2, 4.5, 3.8, 4.7, 4.1]})
print(df)

    Name    City  Sales  Rating
0   Aman   Delhi   5000     4.2
1   Riya  Mumbai   7000     4.5
2  Rahul   Delhi   3000     3.8
3  Priya    Pune   8000     4.7
4   Neha  Mumbai   6000     4.1

In [5]:
#Q1:Select Name and Sales of customers whose Sales are greater than 5000.
df.loc[df['Sales']>5000,['Name','Sales']]

    Name  Sales
1   Riya   7000
3  Priya   8000
4   Neha   6000

In [7]:
#Q2:Select customers who are from Mumbai AND have Sales greater than 6000.
df.loc[(df['City']=='Mumbai') & (df['Sales']>6000)]

   Name    City  Sales  Rating
1  Riya  Mumbai   7000     4.5

In [8]:
#Q3:Select only Name, City and Rating of customers whose Rating is greater than or equal to 4.2.
df.loc[df['Rating']>=4.2,['Name','City','Rating']]

    Name    City  Rating
0   Aman   Delhi     4.2
1   Riya  Mumbai     4.5
3  Priya    Pune     4.7

In [9]:
#Q4:Select customers who are from Delhi OR Pune.Return only Name and City.
df.loc[df['City'].isin(['Delhi','Pune']),['Name','City']]

    Name   City
0   Aman  Delhi
2  Rahul  Delhi
3  Priya   Pune

In [12]:
#Q5:Select rows at positions 1 through 3.
df.iloc[1:4]

    Name    City  Sales  Rating
1   Riya  Mumbai   7000     4.5
2  Rahul   Delhi   3000     3.8
3  Priya    Pune   8000     4.7

In [27]:
#Q6:Select rows at positions 1:4 and only columns at positions 0 and 2.
df.iloc[1:4, [0,2]]

    Name  Sales
1   Riya   7000
2  Rahul   3000
3  Priya   8000

In [28]:
#Q7:Select Priya's Rating using loc.
df.loc[3,'Rating']

np.float64(4.7)

In [29]:
#Q8:Select Neha's City using iloc.
df.iloc[4,1]

'Mumbai'

In [30]:
#Q9:Select Name and Rating of customers who:have Sales ≥ 5000 AND Rating > 4.0
df.loc[(df['Sales']>=5000) &(df['Rating']>4.0),['Name','Rating']]

    Name  Rating
0   Aman     4.2
1   Riya     4.5
3  Priya     4.7
4   Neha     4.1

In [31]:
#Q10:Select Name, Sales and Rating of customers who:are from Mumbai OR Delhi AND have Rating ≥ 4.1
df.loc[df['City'].isin(['Delhi', 'Mumbai']) & (df['Rating'] >= 4.1),['Name', 'Sales', 'Rating']]

   Name  Sales  Rating
0  Aman   5000     4.2
1  Riya   7000     4.5
4  Neha   6000     4.1