Sorting And Ranking Data

In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Downloads\groupby_practice_ecommerce_dataset.csv")
df.head(5)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000

In [2]:
#Q1:Sort the DataFrame by Sales in ascending order.
df.sort_values('Sales')

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000

In [3]:
#Q2:Sort the DataFrame by Sales in descending order.
df.sort_values('Sales',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100

In [4]:
#Q3:Find the 5 orders with the highest Sales.
df.sort_values('Sales',ascending=False).head(5)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000

In [5]:
#Q4:Find the 5 orders with the lowest Sales.
df.sort_values('Sales',ascending=True).head(5)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700

In [6]:
#Q5:Sort the DataFrame by Rating from highest to lowest
df.sort_values('Rating',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000

In [7]:
#Q6:Sort the DataFrame by Rating from lowest to highest.
df.sort_values('Rating',ascending=True)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000

In [8]:
#Q7:Sort the DataFrame alphabetically by City.
df.sort_values('City')

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600

In [9]:
#Q8:Sort the DataFrame alphabetically by Product.
df.sort_values('Product')

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300

In [10]:
#Q9:Sort by City alphabetically and within each city sort Sales from highest to lowest.
df.sort_values(['City','Sales'],ascending=[True,False])

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100

In [12]:
#Q10:Sort by Category alphabetically and then by Sales in descending order.
df.sort_values(['Category','Sales'],ascending=[True,False])

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000

In [13]:
#Q11:Sort by Payment_Mode alphabetically and then by Sales from highest to lowest.
df.sort_values(['Payment_Mode','Sales'],ascending=[True,False])

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600

In [14]:
#Q12:Sort by Order_Status alphabetically and then by Rating from highest to lowest.
df.sort_values(['Order_Status','Rating'],ascending=[True,False])

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700

In [15]:
#Q13:Sort by City alphabetically and then by Rating from highest to lowest.
df.sort_values(['City','Rating'],ascending=[True,False])

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400

In [16]:
#Q14:Display only Delivered orders and sort them by Sales from highest to lowest.
df[df['Order_Status']=='Delivered'].sort_values('Sales',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100

In [17]:
#Q15:Display only orders from Delhi and sort them by Sales descending.
df[df['City']=='Delhi'].sort_values('Sales',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300

In [18]:
#Q16:Display orders where Sales > 1000 and sort them by Sales descending.
df[df['Sales']>1000].sort_values('Sales',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100

In [19]:
#Q17:Display orders where Rating >= 4.5 and sort them by Rating descending.
df[df['Rating']>=4.5].sort_values('Rating',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900

In [20]:
#Q18:Display Delivered orders with Rating >= 4.5, sorted by Sales from highest to lowest.
df[(df['Order_Status']=='Delivered')&(df['Rating']>=4.5)].sort_values('Sales',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700

In [22]:
#Q19:Display orders from Mumbai and sort them by Rating from highest to lowest.
df[df['City']=='Mumbai'].sort_values('Rating',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000

In [23]:
#Q20:Display orders where Payment_Mode == 'UPI' and sort them by Sales descending.
df[df['Payment_Mode']=='UPI'].sort_values('Sales',ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600

In [25]:
#Q21:Sort the DataFrame by its index in ascending order.
df.sort_index()

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600

In [26]:
#Q22:Sort the DataFrame by its index in descending order.
df.sort_index(ascending=False)

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000

In [27]:
#Q23:Set Order_ID as the index and sort the DataFrame by index
df.set_index('Order_ID').sort_index()

,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales
Order_ID,,,,,,,
1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000
1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200
1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500
1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200
1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000
1006,Pune,Home,Mixer,Card,Delivered,4,4500
1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800
1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500
1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000
1010,Delhi,Home,Chair,UPI,Delivered,4,3000
1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700
1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100
1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000
1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200
1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600
1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300
1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000
1018,Pune,Home,Chair,UPI,Delivered,5,3200
1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600
1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400
1021,Pune,Electronics,Mobile,Card,Delivered,4,27500
1022,Delhi,Home,Mixer,UPI,Delivered,5,4800
1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700
1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400
1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000
1026,Mumbai,Home,Chair,UPI,Delivered,4,3100
1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900
1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300
1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000
1030,Pune,Home,Mixer,UPI,Delivered,4,4600

In [28]:
#Q24:Set City as the index and sort the DataFrame by index.
df.set_index('City').sort_index()

,Order_ID,Category,Product,Payment_Mode,Order_Status,Rating,Sales
City,,,,,,,
Delhi,1001,Electronics,Laptop,UPI,Delivered,5,55000
Delhi,1019,Electronics,Headphones,UPI,Cancelled,3,2600
Delhi,1016,Clothing,Jacket,Cash,Delivered,4,3300
Delhi,1013,Electronics,Mobile,Card,Delivered,5,30000
Delhi,1025,Electronics,Laptop,Card,Delivered,5,58000
Delhi,1010,Home,Chair,UPI,Delivered,4,3000
Delhi,1022,Home,Mixer,UPI,Delivered,5,4800
Delhi,1004,Clothing,Jeans,Cash,Cancelled,3,2200
Delhi,1028,Clothing,T-Shirt,Cash,Delivered,4,1300
Delhi,1007,Electronics,Keyboard,UPI,Delivered,4,1800
Mumbai,1008,Clothing,Jacket,Cash,Delivered,5,3500
Mumbai,1026,Home,Chair,UPI,Delivered,4,3100
Mumbai,1023,Electronics,Keyboard,UPI,Delivered,3,1700
Mumbai,1005,Electronics,Mobile,UPI,Delivered,5,28000
Mumbai,1014,Home,Mixer,UPI,Cancelled,2,4200
Mumbai,1029,Electronics,Mobile,Card,Cancelled,2,29000
Mumbai,1017,Electronics,Laptop,Card,Delivered,5,60000
Mumbai,1002,Clothing,T-Shirt,Card,Delivered,4,1200
Mumbai,1020,Clothing,Jeans,Cash,Delivered,4,2400
Mumbai,1011,Electronics,Headphones,UPI,Delivered,5,2700
Pune,1027,Electronics,Headphones,UPI,Delivered,5,2900
Pune,1024,Clothing,Jacket,Cash,Cancelled,2,3400
Pune,1015,Electronics,Keyboard,UPI,Delivered,4,1600
Pune,1018,Home,Chair,UPI,Delivered,5,3200
Pune,1012,Clothing,T-Shirt,Cash,Delivered,3,1100
Pune,1009,Electronics,Laptop,Card,Cancelled,2,52000
Pune,1006,Home,Mixer,Card,Delivered,4,4500
Pune,1003,Electronics,Headphones,UPI,Delivered,4,2500
Pune,1021,Electronics,Mobile,Card,Delivered,4,27500
Pune,1030,Home,Mixer,UPI,Delivered,4,4600

In [35]:
#Q25:Create a Sales_Rank column where the highest Sales gets rank 1.
df['Sales_Rank'] = df['Sales'].rank(ascending=False).astype(int)
df['Sales_Rank']

0      3
1     29
2     22
3     24
4      7
5     11
6     25
7     13
8      4
9     18
10    20
11    30
12     5
13    12
14    27
15    15
16     1
17    16
18    21
19    23
20     8
21     9
22    26
23    14
24     2
25    17
26    19
27    28
28     6
29    10
Name: Sales_Rank, dtype: int64

In [40]:
#Q26:Create a Rating_Rank column where the highest Rating gets rank 1.
df['Rating_Rank']=df['Rating'].rank(ascending=False)
df['Rating_Rank']
df

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000,28.0,5.5
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200,2.0,16.5
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500,9.0,16.5
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200,7.0,24.5
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000,24.0,5.5
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500,20.0,16.5
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800,6.0,16.5
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500,18.0,5.5
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000,27.0,28.5
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000,13.0,16.5
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700,11.0,5.5
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100,1.0,24.5
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000,26.0,5.5
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200,19.0,28.5
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600,4.0,16.5
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300,16.0,16.5
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000,30.0,5.5
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200,15.0,5.5
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600,10.0,24.5
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400,8.0,16.5
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500,23.0,16.5
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800,22.0,5.5
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700,5.0,24.5
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400,17.0,28.5
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000,29.0,5.5
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100,14.0,16.5
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900,12.0,5.5
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300,3.0,16.5
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000,25.0,28.5
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600,21.0,16.5

In [48]:
#Q27:Create a Sales_Rank column where the lowest Sales gets rank 1.
df['Sales_Rank'] = df['Sales'].rank(ascending=True)
df['Sales_Rank']
df

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000,28.0,5.5
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200,2.0,16.5
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500,9.0,16.5
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200,7.0,24.5
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000,24.0,5.5
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500,20.0,16.5
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800,6.0,16.5
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500,18.0,5.5
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000,27.0,28.5
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000,13.0,16.5
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700,11.0,5.5
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100,1.0,24.5
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000,26.0,5.5
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200,19.0,28.5
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600,4.0,16.5
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300,16.0,16.5
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000,30.0,5.5
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200,15.0,5.5
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600,10.0,24.5
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400,8.0,16.5
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500,23.0,16.5
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800,22.0,5.5
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700,5.0,24.5
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400,17.0,28.5
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000,29.0,5.5
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100,14.0,16.5
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900,12.0,5.5
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300,3.0,16.5
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000,25.0,28.5
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600,21.0,16.5

In [49]:
#q28:Display the top 5 orders based on Sales rank.
df[df['Sales'].rank(ascending=False) <= 5]

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000,28.0,5.5
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000,27.0,28.5
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000,26.0,5.5
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000,30.0,5.5
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000,29.0,5.5

In [45]:
#Q29:Display all orders having a Sales_Rank <= 3.
df[df['Sales_Rank']<=3]

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200,2.0,16.5
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100,1.0,24.5
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300,3.0,16.5

In [50]:
#Q30:Create both Sales_Rank and Rating_Rank columns.
df['Sales_Rank'] = df['Sales'].rank(ascending=False)
df['Rating_Rank'] = df['Rating'].rank(ascending=False)
df

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000,3.0,5.5
1,1002,Mumbai,Clothing,T-Shirt,Card,Delivered,4,1200,29.0,16.5
2,1003,Pune,Electronics,Headphones,UPI,Delivered,4,2500,22.0,16.5
3,1004,Delhi,Clothing,Jeans,Cash,Cancelled,3,2200,24.0,24.5
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000,7.0,5.5
5,1006,Pune,Home,Mixer,Card,Delivered,4,4500,11.0,16.5
6,1007,Delhi,Electronics,Keyboard,UPI,Delivered,4,1800,25.0,16.5
7,1008,Mumbai,Clothing,Jacket,Cash,Delivered,5,3500,13.0,5.5
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000,4.0,28.5
9,1010,Delhi,Home,Chair,UPI,Delivered,4,3000,18.0,16.5
10,1011,Mumbai,Electronics,Headphones,UPI,Delivered,5,2700,20.0,5.5
11,1012,Pune,Clothing,T-Shirt,Cash,Delivered,3,1100,30.0,24.5
12,1013,Delhi,Electronics,Mobile,Card,Delivered,5,30000,5.0,5.5
13,1014,Mumbai,Home,Mixer,UPI,Cancelled,2,4200,12.0,28.5
14,1015,Pune,Electronics,Keyboard,UPI,Delivered,4,1600,27.0,16.5
15,1016,Delhi,Clothing,Jacket,Cash,Delivered,4,3300,15.0,16.5
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000,1.0,5.5
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200,16.0,5.5
18,1019,Delhi,Electronics,Headphones,UPI,Cancelled,3,2600,21.0,24.5
19,1020,Mumbai,Clothing,Jeans,Cash,Delivered,4,2400,23.0,16.5
20,1021,Pune,Electronics,Mobile,Card,Delivered,4,27500,8.0,16.5
21,1022,Delhi,Home,Mixer,UPI,Delivered,5,4800,9.0,5.5
22,1023,Mumbai,Electronics,Keyboard,UPI,Delivered,3,1700,26.0,24.5
23,1024,Pune,Clothing,Jacket,Cash,Cancelled,2,3400,14.0,28.5
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000,2.0,5.5
25,1026,Mumbai,Home,Chair,UPI,Delivered,4,3100,17.0,16.5
26,1027,Pune,Electronics,Headphones,UPI,Delivered,5,2900,19.0,5.5
27,1028,Delhi,Clothing,T-Shirt,Cash,Delivered,4,1300,28.0,16.5
28,1029,Mumbai,Electronics,Mobile,Card,Cancelled,2,29000,6.0,28.5
29,1030,Pune,Home,Mixer,UPI,Delivered,4,4600,10.0,16.5

In [57]:
#Q31:Find the highest-selling order in each City.
df.loc[df.groupby('City')['Sales'].idxmax()]

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
24,1025,Delhi,Electronics,Laptop,Card,Delivered,5,58000,2.0,5.5
16,1017,Mumbai,Electronics,Laptop,Card,Delivered,5,60000,1.0,5.5
8,1009,Pune,Electronics,Laptop,Card,Cancelled,2,52000,4.0,28.5

In [58]:
#Q32:Find the highest-rated order in each City.
df.loc[df.groupby('City')['Rating'].idxmax()]

,Order_ID,City,Category,Product,Payment_Mode,Order_Status,Rating,Sales,Sales_Rank,Rating_Rank
0,1001,Delhi,Electronics,Laptop,UPI,Delivered,5,55000,3.0,5.5
4,1005,Mumbai,Electronics,Mobile,UPI,Delivered,5,28000,7.0,5.5
17,1018,Pune,Home,Chair,UPI,Delivered,5,3200,16.0,5.5