Sorting Data

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Downloads\pandas_filtering_practice_dataset.csv")
df.head(5)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497

In [3]:
#Q1:Sort the entire DataFrame by Price in ascending order.
df.sort_values('Price')

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998

In [4]:
#Q2:Sort the entire DataFrame by Price in descending order.
df.sort_values('Price',ascending=False)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499

In [5]:
#Q3:Sort the DataFrame by Rating from lowest to highest.
df.sort_values('Rating')

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497

In [6]:
#Q4:Sort the DataFrame by Rating from highest to lowest.
df.sort_values('Rating',ascending=False)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495

In [7]:
#Q5:Sort the DataFrame by Quantity in descending order.
df.sort_values('Quantity',ascending=False)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499

In [8]:
#Q6:Sort the DataFrame by Total_Amount from highest to lowest.
df.sort_values('Total_Amount',ascending=False)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499

In [9]:
#Q7:Sort the DataFrame by Total_Amount from lowest to highest.
df.sort_values('Total_Amount')

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995

In [10]:
#Q8:Sort by Price descending and display only:Order_ID,Product,Price
df.sort_values('Price',ascending=False)[['Order_ID','Product','Price']]

   Order_ID          Product  Price
24   ORD025    Tennis Racket   3999
19   ORD020           Laptop   3999
14   ORD015         Keyboard   3999
21   ORD022  AI Fundamentals   3999
25   ORD026         Keyboard   2999
29   ORD030        SQL Guide   2999
20   ORD021     Data Science   2999
2    ORD003         Football   2999
7    ORD008       Smartphone   2499
48   ORD049            Chair   2499
45   ORD046          T-Shirt   2499
4    ORD005           Laptop   2499
34   ORD035      Cricket Bat   2499
17   ORD018         Football   2499
18   ORD019            Chair   2499
5    ORD006    Tennis Racket   1999
11   ORD012        SQL Guide   1999
30   ORD031       Smartphone   1999
3    ORD004         Sneakers   1999
35   ORD036         Sneakers   1999
10   ORD011       Smartphone   1999
36   ORD037    Python Basics   1499
26   ORD027       Smartphone   1499
39   ORD040           Jacket   1499
47   ORD048  AI Fundamentals   1499
27   ORD028  AI Fundamentals   1499
0    ORD001       Smartphone   1499
23   ORD024       Smartphone   1499
22   ORD023             Lamp   1499
6    ORD007          T-Shirt   1499
9    ORD010  AI Fundamentals   1499
12   ORD013        SQL Guide   1499
38   ORD039         Yoga Mat    999
37   ORD038       Smartphone    999
8    ORD009            Chair    999
44   ORD045         Keyboard    999
41   ORD042       Headphones    999
49   ORD050            Chair    999
13   ORD014    Python Basics    999
16   ORD017       Smartphone    999
40   ORD041         Yoga Mat    799
15   ORD016         Yoga Mat    799
33   ORD034       Headphones    799
32   ORD033         Football    799
28   ORD029      Cricket Bat    499
42   ORD043           Laptop    499
43   ORD044           Jacket    499
46   ORD047            Chair    499
31   ORD032            Jeans    499
1    ORD002         Keyboard    499

In [11]:
#Q9:Sort by Rating descending and display:Customer,Product,Rating
df.sort_values('Rating',ascending=False)[['Customer','Product','Rating']]

       Customer          Product  Rating
12  Customer_13        SQL Guide     5.0
28  Customer_29      Cricket Bat     4.9
33  Customer_34       Headphones     4.9
20  Customer_21     Data Science     4.9
29  Customer_30        SQL Guide     4.8
44  Customer_45         Keyboard     4.8
34  Customer_35      Cricket Bat     4.8
43  Customer_44           Jacket     4.7
27  Customer_28  AI Fundamentals     4.7
18  Customer_19            Chair     4.7
5   Customer_06    Tennis Racket     4.6
32  Customer_33         Football     4.6
42  Customer_43           Laptop     4.6
46  Customer_47            Chair     4.6
45  Customer_46          T-Shirt     4.5
19  Customer_20           Laptop     4.5
24  Customer_25    Tennis Racket     4.5
31  Customer_32            Jeans     4.4
41  Customer_42       Headphones     4.4
17  Customer_18         Football     4.4
6   Customer_07          T-Shirt     4.4
39  Customer_40           Jacket     4.3
9   Customer_10  AI Fundamentals     4.2
40  Customer_41         Yoga Mat     4.1
13  Customer_14    Python Basics     4.1
48  Customer_49            Chair     4.1
4   Customer_05           Laptop     4.0
49  Customer_50            Chair     4.0
16  Customer_17       Smartphone     3.8
14  Customer_15         Keyboard     3.8
36  Customer_37    Python Basics     3.8
8   Customer_09            Chair     3.8
35  Customer_36         Sneakers     3.6
37  Customer_38       Smartphone     3.6
30  Customer_31       Smartphone     3.6
25  Customer_26         Keyboard     3.5
38  Customer_39         Yoga Mat     3.2
23  Customer_24       Smartphone     3.2
15  Customer_16         Yoga Mat     3.2
2   Customer_03         Football     3.1
26  Customer_27       Smartphone     3.0
7   Customer_08       Smartphone     2.9
3   Customer_04         Sneakers     2.9
21  Customer_22  AI Fundamentals     2.8
11  Customer_12        SQL Guide     2.8
0   Customer_01       Smartphone     2.8
1   Customer_02         Keyboard     2.7
10  Customer_11       Smartphone     2.7
47  Customer_48  AI Fundamentals     2.6
22  Customer_23             Lamp     2.5

In [12]:
#Q10:Sort by Total_Amount descending and display the top 5 orders.
df.sort_values('Total_Amount',ascending=False).head(5)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996

In [13]:
#Q11:Sort by Quantity ascending and display:Order_ID,Product,Quantity
df.sort_values('Quantity')[['Order_ID','Product','Quantity']]

   Order_ID          Product  Quantity
36   ORD037    Python Basics         1
23   ORD024       Smartphone         1
26   ORD027       Smartphone         1
13   ORD014    Python Basics         1
31   ORD032            Jeans         1
32   ORD033         Football         1
19   ORD020           Laptop         1
38   ORD039         Yoga Mat         1
18   ORD019            Chair         1
6    ORD007          T-Shirt         1
5    ORD006    Tennis Racket         1
1    ORD002         Keyboard         1
40   ORD041         Yoga Mat         1
35   ORD036         Sneakers         2
42   ORD043           Laptop         2
45   ORD046          T-Shirt         2
29   ORD030        SQL Guide         2
47   ORD048  AI Fundamentals         2
0    ORD001       Smartphone         2
24   ORD025    Tennis Racket         2
17   ORD018         Football         2
11   ORD012        SQL Guide         2
20   ORD021     Data Science         3
3    ORD004         Sneakers         3
43   ORD044           Jacket         3
4    ORD005           Laptop         3
41   ORD042       Headphones         3
37   ORD038       Smartphone         3
12   ORD013        SQL Guide         3
49   ORD050            Chair         3
48   ORD049            Chair         3
15   ORD016         Yoga Mat         3
25   ORD026         Keyboard         3
30   ORD031       Smartphone         4
46   ORD047            Chair         4
21   ORD022  AI Fundamentals         4
7    ORD008       Smartphone         4
34   ORD035      Cricket Bat         4
10   ORD011       Smartphone         4
33   ORD034       Headphones         4
27   ORD028  AI Fundamentals         4
8    ORD009            Chair         5
14   ORD015         Keyboard         5
16   ORD017       Smartphone         5
22   ORD023             Lamp         5
44   ORD045         Keyboard         5
28   ORD029      Cricket Bat         5
2    ORD003         Football         5
9    ORD010  AI Fundamentals         5
39   ORD040           Jacket         5

In [14]:
#Q12:Sort by Price descending and display only the top 3 most expensive products.
df.sort_values('Price',ascending=False).head(3)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995

In [15]:
#Q13:Sort by City alphabetically, and within each city sort Price from highest to lowest.
df.sort_values(['City','Price'],ascending=[True,False])

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499

In [16]:
#Q14:Sort by Category alphabetically, and within each category sort Rating from highest to lowest
df.sort_values(['Category','Rating'],ascending=[True,False])

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995

In [17]:
#Q15:Sort by Order_Status alphabetically, and within each status sort Total_Amount from highest to lowest.
df.sort_values(['Order_Status','Total_Amount'],ascending=[True,False])

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499

In [18]:
#Q16:Sort by Payment_Mode alphabetically, and within each payment mode sort Price from lowest to highest.
df.sort_values(['Payment_Mode','Price'],ascending=[True,True])

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995

In [19]:
#Q17:Sort by City ascending and then Total_Amount descending.
df.sort_values(['City','Total_Amount'],ascending=[True,False])

,Order_ID,Customer,City,Category,Product,Quantity,Price,Rating,Payment_Mode,Order_Status,Total_Amount
48,ORD049,Customer_49,Bangalore,Home,Chair,3,2499,4.1,Net Banking,Pending,7497
39,ORD040,Customer_40,Bangalore,Clothing,Jacket,5,1499,4.3,Card,Delivered,7495
44,ORD045,Customer_45,Bangalore,Electronics,Keyboard,5,999,4.8,Card,Delivered,4995
35,ORD036,Customer_36,Bangalore,Clothing,Sneakers,2,1999,3.6,UPI,Delivered,3998
47,ORD048,Customer_48,Bangalore,Books,AI Fundamentals,2,1499,2.6,Card,Cancelled,2998
41,ORD042,Customer_42,Bangalore,Electronics,Headphones,3,999,4.4,Net Banking,Pending,2997
31,ORD032,Customer_32,Bangalore,Clothing,Jeans,1,499,4.4,UPI,Delivered,499
21,ORD022,Customer_22,Chennai,Books,AI Fundamentals,4,3999,2.8,Card,Delivered,15996
25,ORD026,Customer_26,Chennai,Electronics,Keyboard,3,2999,3.5,UPI,Delivered,8997
3,ORD004,Customer_04,Chennai,Clothing,Sneakers,3,1999,2.9,Cash,Delivered,5997
8,ORD009,Customer_09,Chennai,Home,Chair,5,999,3.8,Card,Delivered,4995
16,ORD017,Customer_17,Chennai,Electronics,Smartphone,5,999,3.8,UPI,Delivered,4995
33,ORD034,Customer_34,Chennai,Electronics,Headphones,4,799,4.9,Card,Pending,3196
6,ORD007,Customer_07,Chennai,Clothing,T-Shirt,1,1499,4.4,UPI,Delivered,1499
2,ORD003,Customer_03,Delhi,Sports,Football,5,2999,3.1,Cash,Delivered,14995
34,ORD035,Customer_35,Delhi,Sports,Cricket Bat,4,2499,4.8,Card,Delivered,9996
22,ORD023,Customer_23,Delhi,Home,Lamp,5,1499,2.5,UPI,Delivered,7495
0,ORD001,Customer_01,Delhi,Electronics,Smartphone,2,1499,2.8,UPI,Pending,2998
49,ORD050,Customer_50,Delhi,Home,Chair,3,999,4.0,Cash,Delivered,2997
28,ORD029,Customer_29,Delhi,Sports,Cricket Bat,5,499,4.9,Card,Delivered,2495
5,ORD006,Customer_06,Delhi,Sports,Tennis Racket,1,1999,4.6,Cash,Pending,1999
23,ORD024,Customer_24,Delhi,Electronics,Smartphone,1,1499,3.2,Net Banking,Delivered,1499
43,ORD044,Customer_44,Delhi,Clothing,Jacket,3,499,4.7,Card,Delivered,1497
13,ORD014,Customer_14,Delhi,Books,Python Basics,1,999,4.1,Net Banking,Pending,999
38,ORD039,Customer_39,Delhi,Sports,Yoga Mat,1,999,3.2,UPI,Pending,999
42,ORD043,Customer_43,Delhi,Electronics,Laptop,2,499,4.6,Card,Cancelled,998
14,ORD015,Customer_15,Hyderabad,Electronics,Keyboard,5,3999,3.8,UPI,Delivered,19995
7,ORD008,Customer_08,Hyderabad,Electronics,Smartphone,4,2499,2.9,Cash,Delivered,9996
30,ORD031,Customer_31,Hyderabad,Electronics,Smartphone,4,1999,3.6,Net Banking,Delivered,7996
4,ORD005,Customer_05,Hyderabad,Electronics,Laptop,3,2499,4.0,UPI,Cancelled,7497
9,ORD010,Customer_10,Hyderabad,Books,AI Fundamentals,5,1499,4.2,UPI,Delivered,7495
29,ORD030,Customer_30,Hyderabad,Books,SQL Guide,2,2999,4.8,Card,Cancelled,5998
45,ORD046,Customer_46,Hyderabad,Clothing,T-Shirt,2,2499,4.5,Net Banking,Delivered,4998
11,ORD012,Customer_12,Hyderabad,Books,SQL Guide,2,1999,2.8,Cash,Pending,3998
18,ORD019,Customer_19,Hyderabad,Home,Chair,1,2499,4.7,Cash,Delivered,2499
26,ORD027,Customer_27,Hyderabad,Electronics,Smartphone,1,1499,3.0,Net Banking,Delivered,1499
32,ORD033,Customer_33,Hyderabad,Sports,Football,1,799,4.6,UPI,Pending,799
40,ORD041,Customer_41,Hyderabad,Sports,Yoga Mat,1,799,4.1,Cash,Delivered,799
10,ORD011,Customer_11,Kolkata,Electronics,Smartphone,4,1999,2.7,Cash,Delivered,7996
15,ORD016,Customer_16,Kolkata,Sports,Yoga Mat,3,799,3.2,Card,Cancelled,2397
24,ORD025,Customer_25,Mumbai,Sports,Tennis Racket,2,3999,4.5,Card,Delivered,7998
27,ORD028,Customer_28,Mumbai,Books,AI Fundamentals,4,1499,4.7,UPI,Cancelled,5996
19,ORD020,Customer_20,Mumbai,Electronics,Laptop,1,3999,4.5,Card,Delivered,3999
37,ORD038,Customer_38,Mumbai,Electronics,Smartphone,3,999,3.6,Cash,Pending,2997
46,ORD047,Customer_47,Mumbai,Home,Chair,4,499,4.6,Card,Delivered,1996
20,ORD021,Customer_21,Pune,Books,Data Science,3,2999,4.9,Card,Delivered,8997
17,ORD018,Customer_18,Pune,Sports,Football,2,2499,4.4,UPI,Pending,4998
12,ORD013,Customer_13,Pune,Books,SQL Guide,3,1499,5.0,Card,Pending,4497
36,ORD037,Customer_37,Pune,Books,Python Basics,1,1499,3.8,Card,Delivered,1499
1,ORD002,Customer_02,Pune,Electronics,Keyboard,1,499,2.7,Card,Pending,499

In [30]:
#Q18:Find the 5 highest-value orders based on Total_Amount.
df.sort_values('Total_Amount',ascending=False).head(5)[['Order_ID', 'Customer', 'City', 'Product', 'Total_Amount']]

   Order_ID     Customer       City          Product  Total_Amount
14   ORD015  Customer_15  Hyderabad         Keyboard         19995
21   ORD022  Customer_22    Chennai  AI Fundamentals         15996
2    ORD003  Customer_03      Delhi         Football         14995
7    ORD008  Customer_08  Hyderabad       Smartphone          9996
34   ORD035  Customer_35      Delhi      Cricket Bat          9996

In [23]:
#Q19:Find the 3 most expensive products based on Price.
df.sort_values('Price',ascending=False).head(3)[['Product','Price']]

          Product  Price
24  Tennis Racket   3999
19         Laptop   3999
14       Keyboard   3999

In [31]:
#Q20:Find the 5 orders with the highest ratings
df.sort_values('Rating',ascending=False).head(5)[['Order_ID', 'Customer', 'Product', 'Rating']]

   Order_ID     Customer       Product  Rating
12   ORD013  Customer_13     SQL Guide     5.0
28   ORD029  Customer_29   Cricket Bat     4.9
33   ORD034  Customer_34    Headphones     4.9
20   ORD021  Customer_21  Data Science     4.9
29   ORD030  Customer_30     SQL Guide     4.8

In [32]:
#Q21:Find the 3 orders with the largest quantities.
df.sort_values('Quantity',ascending=False).head(3)[['Order_ID', 'Product', 'Quantity']]

   Order_ID      Product  Quantity
8    ORD009        Chair         5
28   ORD029  Cricket Bat         5
14   ORD015     Keyboard         5

In [33]:
#Q22:Sort the data by Category ascending and Total_Amount descending, then display only:Category, Product, Quantity, Total_Amount
df.sort_values(['Category','Total_Amount'],ascending=[True,False])[['Category','Product','Quantity','Total_Amount']]

       Category          Product  Quantity  Total_Amount
21        Books  AI Fundamentals         4         15996
20        Books     Data Science         3          8997
9         Books  AI Fundamentals         5          7495
29        Books        SQL Guide         2          5998
27        Books  AI Fundamentals         4          5996
12        Books        SQL Guide         3          4497
11        Books        SQL Guide         2          3998
47        Books  AI Fundamentals         2          2998
36        Books    Python Basics         1          1499
13        Books    Python Basics         1           999
39     Clothing           Jacket         5          7495
3      Clothing         Sneakers         3          5997
45     Clothing          T-Shirt         2          4998
35     Clothing         Sneakers         2          3998
6      Clothing          T-Shirt         1          1499
43     Clothing           Jacket         3          1497
31     Clothing            Jeans         1           499
14  Electronics         Keyboard         5         19995
7   Electronics       Smartphone         4          9996
25  Electronics         Keyboard         3          8997
10  Electronics       Smartphone         4          7996
30  Electronics       Smartphone         4          7996
4   Electronics           Laptop         3          7497
16  Electronics       Smartphone         5          4995
44  Electronics         Keyboard         5          4995
19  Electronics           Laptop         1          3999
33  Electronics       Headphones         4          3196
0   Electronics       Smartphone         2          2998
37  Electronics       Smartphone         3          2997
41  Electronics       Headphones         3          2997
23  Electronics       Smartphone         1          1499
26  Electronics       Smartphone         1          1499
42  Electronics           Laptop         2           998
1   Electronics         Keyboard         1           499
48         Home            Chair         3          7497
22         Home             Lamp         5          7495
8          Home            Chair         5          4995
49         Home            Chair         3          2997
18         Home            Chair         1          2499
46         Home            Chair         4          1996
2        Sports         Football         5         14995
34       Sports      Cricket Bat         4          9996
24       Sports    Tennis Racket         2          7998
17       Sports         Football         2          4998
28       Sports      Cricket Bat         5          2495
15       Sports         Yoga Mat         3          2397
5        Sports    Tennis Racket         1          1999
38       Sports         Yoga Mat         1           999
32       Sports         Football         1           799
40       Sports         Yoga Mat         1           799

In [34]:
#Q23:Sort by Order_Status and then Rating descending. Display:Order_ID, Product, Rating, Order_Status
df.sort_values(['Order_Status','Rating'],ascending=[True,False])[['Order_ID','Product','Rating','Order_Status']]

   Order_ID          Product  Rating Order_Status
29   ORD030        SQL Guide     4.8    Cancelled
27   ORD028  AI Fundamentals     4.7    Cancelled
42   ORD043           Laptop     4.6    Cancelled
4    ORD005           Laptop     4.0    Cancelled
15   ORD016         Yoga Mat     3.2    Cancelled
47   ORD048  AI Fundamentals     2.6    Cancelled
20   ORD021     Data Science     4.9    Delivered
28   ORD029      Cricket Bat     4.9    Delivered
34   ORD035      Cricket Bat     4.8    Delivered
44   ORD045         Keyboard     4.8    Delivered
18   ORD019            Chair     4.7    Delivered
43   ORD044           Jacket     4.7    Delivered
46   ORD047            Chair     4.6    Delivered
19   ORD020           Laptop     4.5    Delivered
24   ORD025    Tennis Racket     4.5    Delivered
45   ORD046          T-Shirt     4.5    Delivered
6    ORD007          T-Shirt     4.4    Delivered
31   ORD032            Jeans     4.4    Delivered
39   ORD040           Jacket     4.3    Delivered
9    ORD010  AI Fundamentals     4.2    Delivered
40   ORD041         Yoga Mat     4.1    Delivered
49   ORD050            Chair     4.0    Delivered
8    ORD009            Chair     3.8    Delivered
14   ORD015         Keyboard     3.8    Delivered
16   ORD017       Smartphone     3.8    Delivered
36   ORD037    Python Basics     3.8    Delivered
30   ORD031       Smartphone     3.6    Delivered
35   ORD036         Sneakers     3.6    Delivered
25   ORD026         Keyboard     3.5    Delivered
23   ORD024       Smartphone     3.2    Delivered
2    ORD003         Football     3.1    Delivered
26   ORD027       Smartphone     3.0    Delivered
3    ORD004         Sneakers     2.9    Delivered
7    ORD008       Smartphone     2.9    Delivered
21   ORD022  AI Fundamentals     2.8    Delivered
10   ORD011       Smartphone     2.7    Delivered
22   ORD023             Lamp     2.5    Delivered
12   ORD013        SQL Guide     5.0      Pending
33   ORD034       Headphones     4.9      Pending
5    ORD006    Tennis Racket     4.6      Pending
32   ORD033         Football     4.6      Pending
17   ORD018         Football     4.4      Pending
41   ORD042       Headphones     4.4      Pending
13   ORD014    Python Basics     4.1      Pending
48   ORD049            Chair     4.1      Pending
37   ORD038       Smartphone     3.6      Pending
38   ORD039         Yoga Mat     3.2      Pending
0    ORD001       Smartphone     2.8      Pending
11   ORD012        SQL Guide     2.8      Pending
1    ORD002         Keyboard     2.7      Pending

In [35]:
#Q24:Sort by City ascending and Price descending. Display:City, Product, Price
df.sort_values(['City','Price'],ascending=[True,False])[['City','Product','Price']]

         City          Product  Price
48  Bangalore            Chair   2499
35  Bangalore         Sneakers   1999
39  Bangalore           Jacket   1499
47  Bangalore  AI Fundamentals   1499
41  Bangalore       Headphones    999
44  Bangalore         Keyboard    999
31  Bangalore            Jeans    499
21    Chennai  AI Fundamentals   3999
25    Chennai         Keyboard   2999
3     Chennai         Sneakers   1999
6     Chennai          T-Shirt   1499
8     Chennai            Chair    999
16    Chennai       Smartphone    999
33    Chennai       Headphones    799
2       Delhi         Football   2999
34      Delhi      Cricket Bat   2499
5       Delhi    Tennis Racket   1999
0       Delhi       Smartphone   1499
22      Delhi             Lamp   1499
23      Delhi       Smartphone   1499
13      Delhi    Python Basics    999
38      Delhi         Yoga Mat    999
49      Delhi            Chair    999
28      Delhi      Cricket Bat    499
42      Delhi           Laptop    499
43      Delhi           Jacket    499
14  Hyderabad         Keyboard   3999
29  Hyderabad        SQL Guide   2999
4   Hyderabad           Laptop   2499
7   Hyderabad       Smartphone   2499
18  Hyderabad            Chair   2499
45  Hyderabad          T-Shirt   2499
11  Hyderabad        SQL Guide   1999
30  Hyderabad       Smartphone   1999
9   Hyderabad  AI Fundamentals   1499
26  Hyderabad       Smartphone   1499
32  Hyderabad         Football    799
40  Hyderabad         Yoga Mat    799
10    Kolkata       Smartphone   1999
15    Kolkata         Yoga Mat    799
19     Mumbai           Laptop   3999
24     Mumbai    Tennis Racket   3999
27     Mumbai  AI Fundamentals   1499
37     Mumbai       Smartphone    999
46     Mumbai            Chair    499
20       Pune     Data Science   2999
17       Pune         Football   2499
12       Pune        SQL Guide   1499
36       Pune    Python Basics   1499
1        Pune         Keyboard    499

In [36]:
#Q25:Sort by Payment_Mode ascending and Total_Amount descending. Display:Payment_Mode, Order_ID, Total_Amount
df.sort_values(['Payment_Mode','Total_Amount'],ascending=[True,False])[['Payment_Mode','Order_ID','Total_Amount']]

   Payment_Mode Order_ID  Total_Amount
21         Card   ORD022         15996
34         Card   ORD035          9996
20         Card   ORD021          8997
24         Card   ORD025          7998
39         Card   ORD040          7495
29         Card   ORD030          5998
8          Card   ORD009          4995
44         Card   ORD045          4995
12         Card   ORD013          4497
19         Card   ORD020          3999
33         Card   ORD034          3196
47         Card   ORD048          2998
28         Card   ORD029          2495
15         Card   ORD016          2397
46         Card   ORD047          1996
36         Card   ORD037          1499
43         Card   ORD044          1497
42         Card   ORD043           998
1          Card   ORD002           499
2          Cash   ORD003         14995
7          Cash   ORD008          9996
10         Cash   ORD011          7996
3          Cash   ORD004          5997
11         Cash   ORD012          3998
37         Cash   ORD038          2997
49         Cash   ORD050          2997
18         Cash   ORD019          2499
5          Cash   ORD006          1999
40         Cash   ORD041           799
30  Net Banking   ORD031          7996
48  Net Banking   ORD049          7497
45  Net Banking   ORD046          4998
41  Net Banking   ORD042          2997
23  Net Banking   ORD024          1499
26  Net Banking   ORD027          1499
13  Net Banking   ORD014           999
14          UPI   ORD015         19995
25          UPI   ORD026          8997
4           UPI   ORD005          7497
9           UPI   ORD010          7495
22          UPI   ORD023          7495
27          UPI   ORD028          5996
17          UPI   ORD018          4998
16          UPI   ORD017          4995
35          UPI   ORD036          3998
0           UPI   ORD001          2998
6           UPI   ORD007          1499
38          UPI   ORD039           999
32          UPI   ORD033           799
31          UPI   ORD032           499

In [37]:
'''Q26:Create a result that shows the top 5 highest-value orders, but display only:
Order_ID, Customer, City, Product, Quantity, Price, Rating, Total_Amount
Sort the result by Total_Amount from highest to lowest.'''

df.sort_values('Total_Amount',ascending=False).head(5)[['Order_ID', 'Customer', 'City',
            'Product', 'Quantity', 'Price', 'Rating', 'Total_Amount']]

,Order_ID,Customer,City,Product,Quantity,Price,Rating,Total_Amount
14,ORD015,Customer_15,Hyderabad,Keyboard,5,3999,3.8,19995
21,ORD022,Customer_22,Chennai,AI Fundamentals,4,3999,2.8,15996
2,ORD003,Customer_03,Delhi,Football,5,2999,3.1,14995
7,ORD008,Customer_08,Hyderabad,Smartphone,4,2499,2.9,9996
34,ORD035,Customer_35,Delhi,Cricket Bat,4,2499,4.8,9996